Assertion failed
CallStack (from HasCallStack):
  assert, called at assert.hs:9:11 in main:Main

